// <auto-generated />
using System;
using HRIS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRIS.Data.Migrations
{
    [DbContext(typeof(HRContext))]
    [Migration("20210924210122_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRIS.Domain.RV.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AcceptedByHR")
                        .HasColumnType("bit");

                    b.Property<string>("AccessibleLogins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccessiblePositions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Acting")
                        .HasColumnType("bit");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivisionNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpIdNoZero")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EndofEmployment")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HRApproval")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDirectReport")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Locn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PositionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RVEmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("Rehire")
                        .HasColumnType("bit");

                    b.Property<string>("ReportsTo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReportsTo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToEMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToEMail2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToEmpId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToEmpId2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToFirstName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToFullName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToLastName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToLogin2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToPhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToPreferredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsToPreferredName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperLoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkZone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employee", "RV");
                });

            modelBuilder.Entity("HRIS.Domain.TRN.TrainingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AchievementType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Building")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoursDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DevelopmentGoal")
                        .HasColumnType("bit");

                    b.Property<string>("EDEmpId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Locn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MangerEmpId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OutofProvince")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgressStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RationalForAttending")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestorLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReuglarHour")
                        .HasColumnType("bit");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("TrnHours")
                        .HasColumnType("real");

                    b.Property<string>("TrnLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrnOption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrnProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrnType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkZone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrainingRequest", "TRN");
                });
#pragma warning restore 612, 618
        }
    }
}
