CREATE TABLE [TRN].[TrainingRequest] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [RequestId]            NVARCHAR (MAX) NULL,
    [FirstName]            NVARCHAR (50)  NOT NULL,
    [LastName]             NVARCHAR (50)  NOT NULL,
    [PreferredName]        NVARCHAR (MAX) NULL,
    [FullName]             NVARCHAR (MAX) NULL,
    [LoginName]            NVARCHAR (MAX) NULL,
    [EMail]                NVARCHAR (MAX) NULL,
    [Section]              NVARCHAR (MAX) NULL,
    [Locn]                 NVARCHAR (MAX) NULL,
    [Department]           NVARCHAR (MAX) NULL,
    [PositionCode]         NVARCHAR (MAX) NULL,
    [PositionDesc]         NVARCHAR (MAX) NULL,
    [WorkZone]             NVARCHAR (MAX) NULL,
    [Building]             NVARCHAR (MAX) NULL,
    [Phone]                NVARCHAR (MAX) NULL,
    [GLCode]               NVARCHAR (MAX) NULL,
    [MangerEmpId]          NVARCHAR (MAX) NULL,
    [ManagerFullName]      NVARCHAR (MAX) NULL,
    [EDEmpId]              NVARCHAR (MAX) NULL,
    [EDFullName]           NVARCHAR (MAX) NULL,
    [TrnName]              NVARCHAR (MAX) NULL,
    [TrnType]              NVARCHAR (MAX) NULL,
    [TrnProvider]          NVARCHAR (MAX) NULL,
    [AchievementType]      NVARCHAR (MAX) NULL,
    [TrnLocation]          NVARCHAR (MAX) NULL,
    [StartDate]            DATETIME2 (7)  NOT NULL,
    [EndDate]              DATETIME2 (7)  NOT NULL,
    [TrnOption]            NVARCHAR (MAX) NULL,
    [DevelopmentGoal]      BIT            NOT NULL,
    [ReuglarHour]          BIT            NOT NULL,
    [OutofProvince]        BIT            NOT NULL,
    [TrnHours]             REAL           NOT NULL,
    [CoursDetails]         NVARCHAR (MAX) NULL,
    [RationalForAttending] NVARCHAR (MAX) NULL,
    [RequestorLogin]       NVARCHAR (MAX) NULL,
    [RequestedDate]        DATETIME2 (7)  NOT NULL,
    [ApprovalStatus]       NVARCHAR (MAX) NULL,
    [ProgressStatus]       NVARCHAR (MAX) NULL,
    [CreatedDate]          DATETIME2 (7)  NOT NULL,
    [CreatedBy]            NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_TrainingRequest] PRIMARY KEY CLUSTERED ([Id] ASC)
);

