CREATE TABLE [RV].[Employee] (
    [Id]                      INT             IDENTITY (1, 1) NOT NULL,
    [EmployeeId]              NVARCHAR (MAX)  NULL,
    [EmpIdNoZero]             INT             NULL,
    [RVEmployeeId]            INT             NULL,
    [Active]                  NVARCHAR (MAX)  NULL,
    [FirstName]               NVARCHAR (50)   NOT NULL,
    [LastName]                NVARCHAR (50)   NOT NULL,
    [PreferredName]           NVARCHAR (MAX)  NULL,
    [FullName]                NVARCHAR (MAX)  NULL,
    [LoginName]               NVARCHAR (MAX)  NULL,
    [SuperLoginName]          NVARCHAR (MAX)  NULL,
    [EMail]                   NVARCHAR (MAX)  NULL,
    [Section]                 NVARCHAR (MAX)  NULL,
    [Locn]                    NVARCHAR (MAX)  NULL,
    [Department]              NVARCHAR (MAX)  NULL,
    [PositionCode]            NVARCHAR (MAX)  NULL,
    [PositionDesc]            NVARCHAR (MAX)  NULL,
    [WorkZone]                NVARCHAR (MAX)  NULL,
    [Building]                NVARCHAR (MAX)  NULL,
    [Phone]                   NVARCHAR (MAX)  NULL,
    [GLCode]                  NVARCHAR (MAX)  NULL,
    [Status]                  NVARCHAR (MAX)  NULL,
    [Picture]                 VARBINARY (MAX) NULL,
    [AccessiblePositions]     NVARCHAR (MAX)  NULL,
    [AccessibleLogins]        NVARCHAR (MAX)  NULL,
    [Acting]                  BIT             NOT NULL,
    [Rehire]                  BIT             NOT NULL,
    [EndofEmployment]         BIT             NOT NULL,
    [AcceptedByHR]            BIT             NOT NULL,
    [ReportsTo]               NVARCHAR (50)   NULL,
    [ReportsToDesc]           NVARCHAR (MAX)  NULL,
    [ReportsToEmpId]          NVARCHAR (MAX)  NULL,
    [ReportsToFirstName]      NVARCHAR (MAX)  NULL,
    [ReportsToLastName]       NVARCHAR (MAX)  NULL,
    [ReportsToPreferredName]  NVARCHAR (MAX)  NULL,
    [ReportsToFullName]       NVARCHAR (MAX)  NULL,
    [ReportsToLogin]          NVARCHAR (MAX)  NULL,
    [ReportsToEMail]          NVARCHAR (MAX)  NULL,
    [ReportsToPhone]          NVARCHAR (MAX)  NULL,
    [ReportsTo2]              NVARCHAR (MAX)  NULL,
    [ReportsToEmpId2]         NVARCHAR (MAX)  NULL,
    [ReportsToLogin2]         NVARCHAR (MAX)  NULL,
    [ReportsToEMail2]         NVARCHAR (MAX)  NULL,
    [ReportsToPhone2]         NVARCHAR (MAX)  NULL,
    [ReportsToFirstName2]     NVARCHAR (MAX)  NULL,
    [ReportsToLastName2]      NVARCHAR (MAX)  NULL,
    [ReportsToPreferredName2] NVARCHAR (MAX)  NULL,
    [ReportsToFullName2]      NVARCHAR (MAX)  NULL,
    [PositionType]            NVARCHAR (MAX)  NULL,
    [HRApproval]              BIT             NOT NULL,
    [IsDirectReport]          BIT             NOT NULL,
    [Division]                NVARCHAR (MAX)  NULL,
    [DivisionNum]             NVARCHAR (MAX)  NULL,
    [CreatedUser]             NVARCHAR (MAX)  NULL,
    [CreatedTime]             DATETIME2 (7)   NULL,
    [UpdatedUser]             NVARCHAR (MAX)  NULL,
    [UpdatedTime]             DATETIME2 (7)   NULL,
    CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED ([Id] ASC)
);

